theme = "docdock"
baseURL = "https://ned14.github.io/outcome/"
title = "Outcome documentation"
publishDir = "../html"
pygmentsStyle = "vs"
pygmentsUseClasses = true

[outputs]
  home = [ "HTML", "RSS", "JSON"]
  
[params]
  editURL = "https://github.com/ned14/outcome/edit/develop/doc/src/content/"
  
[[menu.shortcuts]]
  pre = "<h3>More</h3>"
  name = "<i class='fa fa-github'></i> Outcome 2.0 github repo"
  identifier = "ds"
  url = "https://github.com/ned14/outcome"
  weight = 10
  
[[menu.shortcuts]]
  name = "<i class='fa fa-bullhorn'></i> Acknowledgements"
  url = "/credits"
  weight = 30